//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sentio.Grid.Executor.RemoteServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RemoteServices.IDeploymentService")]
    public interface IDeploymentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeploymentService/GetInstalledApplications", ReplyAction="http://tempuri.org/IDeploymentService/GetInstalledApplicationsResponse")]
        Sentio.Grid.Common.ApplicationDefinition[] GetInstalledApplications();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeploymentService/IsApplicationInstalledByID", ReplyAction="http://tempuri.org/IDeploymentService/IsApplicationInstalledByIDResponse")]
        bool IsApplicationInstalledByID(System.Guid applicationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeploymentService/IsApplicationInstalledByName", ReplyAction="http://tempuri.org/IDeploymentService/IsApplicationInstalledByNameResponse")]
        bool IsApplicationInstalledByName(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IDeploymentServiceChannel : Sentio.Grid.Executor.RemoteServices.IDeploymentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class DeploymentServiceClient : System.ServiceModel.ClientBase<Sentio.Grid.Executor.RemoteServices.IDeploymentService>, Sentio.Grid.Executor.RemoteServices.IDeploymentService {
        
        public DeploymentServiceClient() {
        }
        
        public DeploymentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DeploymentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeploymentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeploymentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Sentio.Grid.Common.ApplicationDefinition[] GetInstalledApplications() {
            return base.Channel.GetInstalledApplications();
        }
        
        public bool IsApplicationInstalledByID(System.Guid applicationId) {
            return base.Channel.IsApplicationInstalledByID(applicationId);
        }
        
        public bool IsApplicationInstalledByName(string name) {
            return base.Channel.IsApplicationInstalledByName(name);
        }
    }
}
