//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sentio.Grid.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sentio.Grid.Common.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawny plik aplikacji. Aplikacja nie zawiera swojej definicji..
        /// </summary>
        internal static string InvalidApplicationNoDefinition {
            get {
                return ResourceManager.GetString("InvalidApplicationNoDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawny katalog instalacji aplikacji. Proszę się upewnić, że opcja [Application.StoragePath] wskazuje na poprawny katalog..
        /// </summary>
        internal static string InvalidDeploymentPath {
            get {
                return ResourceManager.GetString("InvalidDeploymentPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie ma jeszcze zainstalowanych aplikacji..
        /// </summary>
        internal static string NoApplicationsInstalled1 {
            get {
                return ResourceManager.GetString("NoApplicationsInstalled1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosze zdefiniować ścieżkę instalacji aplikacji. Opcia [Applications.StoragePath] w appSettings..
        /// </summary>
        internal static string NoDeploymentPath {
            get {
                return ResourceManager.GetString("NoDeploymentPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; nie jest poprawna komenda..
        /// </summary>
        internal static string UnkonwnCommand {
            get {
                return ResourceManager.GetString("UnkonwnCommand", resourceCulture);
            }
        }
    }
}
